variables:
  PROJECT_ROOT: /web/apps

stages:
  - checkfmt
  - deploytest

checkfmt:
  stage: checkfmt
  before_script:
  - cd $PROJECT_ROOT
  - git checkout test
  - git pull --rebase
  script:
    - make checkgofmt
  tags:
    - ginsmart_fmt
  
deploytest:
  stage: deploytest
  before_script:
    - cd $PROJECT_ROOT
    - git checkout test
  script:
    - git pull --rebase
    - make checkgofmt
    - ./deploy/ci_run.sh restart
  tags:
    - ginsmart_deploy
  only:
    - test
  except:
    - master