
[env]
env="debug"
[server]
# 服务监听地址
listen=":8081"

[mysql]
host="127.0.0.1:3306"
user="root"
password="123456"
# 运行前确保这个库已经创建了
dbname="test"

#[redis]
#host="127.0.0.1:6379"
#password=""
#db=0
#size=100

[jwt]
expire=864000000

